import dotenv from "dotenv";

dotenv.config();

 
enum ENVIRONMENT_VARIABLES {
  SERVER_PORT = "SERVER_PORT",
  DATABASE_NAME = "DATABASE_NAME",
  DATABASE_USERNAME = "DATABASE_USERNAME",
  DATABASE_PASSWORD = "DATABASE_PASSWORD",
  DATABASE_HOST = "DATABASE_HOST",
  DATABASE_PORT = "DATABASE_PORT",
  IS_PRODUCTION = "IS_PRODUCTION",
  NODE_ENV = "NODE_ENV",
  GATEWAY_SECRET_KEY= 'GATEWAY_SECRET_KEY',
  JOB_NAME='JOB_NAME',
  RABBITMQ_URL='RABBITMQ_URL',
  QUEUE_NAME='QUEUE_NAME',
   QUEUE_NAME_RMQ ='QUEUE_NAME_RMQ',
  QUEUE_NAME_RMQ_1='QUEUE_NAME_RMQ_1',
  QUEUE_NAME_RMQ_2='QUEUE_NAME_RMQ_2',
  REDIS_PASSWORD='REDIS_PASSWORD',
  REDIS_HOST='REDIS_HOST',
  REDIS_PORT='REDIS_PORT',
  REDIS_USERNAME='REDIS_USERNAME',
  RMQ_HOST_NAME='RMQ_HOST_NAME',
  PROM_EXCHANGE_NAME='PROM_EXCHANGE_NAME'

}

function getEnv(variableName: ENVIRONMENT_VARIABLES) {
  const envKey = ENVIRONMENT_VARIABLES[variableName];
  const foundEnv = process.env[envKey];
  const message = `${envKey} was not found`;
  if (!foundEnv) {
    console.log(message);
    throw Error(message);
  }
  return foundEnv;
}

export const APP_CONFIGS = {
  
  SERVER_PORT: getEnv(ENVIRONMENT_VARIABLES.SERVER_PORT),
  NODE_ENV: getEnv(ENVIRONMENT_VARIABLES.NODE_ENV),
  DATABASE_NAME: getEnv(ENVIRONMENT_VARIABLES.DATABASE_NAME),
  DATABASE_USERNAME: getEnv(ENVIRONMENT_VARIABLES.DATABASE_USERNAME),
  DATABASE_PASSWORD: getEnv(ENVIRONMENT_VARIABLES.DATABASE_PASSWORD),
  DATABASE_HOST: getEnv(ENVIRONMENT_VARIABLES.DATABASE_HOST),
  DATABASE_PORT: getEnv(ENVIRONMENT_VARIABLES.DATABASE_PORT),
  IS_PRODUCTION: getEnv(ENVIRONMENT_VARIABLES.IS_PRODUCTION),
  GATEWAY_SECRET_KEY: getEnv(ENVIRONMENT_VARIABLES.GATEWAY_SECRET_KEY),
  RABBITMQ_URL: getEnv(ENVIRONMENT_VARIABLES.RABBITMQ_URL),
  JOB_NAME: getEnv(ENVIRONMENT_VARIABLES.JOB_NAME),
  QUEUE_NAME: getEnv(ENVIRONMENT_VARIABLES.QUEUE_NAME),
   QUEUE_NAME_RMQ: getEnv(ENVIRONMENT_VARIABLES.QUEUE_NAME_RMQ),
  QUEUE_NAME_RMQ_1: getEnv(ENVIRONMENT_VARIABLES.QUEUE_NAME_RMQ_1),
   QUEUE_NAME_RMQ_2: getEnv(ENVIRONMENT_VARIABLES.QUEUE_NAME_RMQ_2),
  REDIS_PASSWORD:getEnv(ENVIRONMENT_VARIABLES.REDIS_PASSWORD),
  REDIS_HOST: getEnv(ENVIRONMENT_VARIABLES.REDIS_HOST),
  REDIS_PORT: getEnv(ENVIRONMENT_VARIABLES.REDIS_PORT),
  REDIS_USERNAME: getEnv(ENVIRONMENT_VARIABLES.REDIS_USERNAME),
  RMQ_HOST_NAME: getEnv(ENVIRONMENT_VARIABLES.RMQ_HOST_NAME),
  PROM_EXCHANGE_NAME: getEnv(ENVIRONMENT_VARIABLES.PROM_EXCHANGE_NAME)
  
};
